### ISSUE TITLE
Backend challenge newline inconsistency

### ISSUE THREAD

**Issue by watsonbox** [watsonbox/drivy_jobs#1]
@nmondollot Admittedly only a very small issue, but I noticed that the `output.json` for levels 1-4 ends with a newline char, but for levels 5 and 6 does not.

Was just about to raise this issue against the main repo but realised I probably shouldn't :relieved:.  Nice challenge btw I enjoyed working through this.

**Comment by nmondollot** [comment]
thanks for the feedback, we'll fix this asap!

**Comment by nmondollot** [comment]
done
https://github.com/drivy/jobs/commit/c4a74613f7db06b2caea9fdb6f62c170dc774c94

**Comment by watsonbox** [comment]
Sweet, thx.
